# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [ ]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [8]:
print(np.__version__)
np.show_config()


2.2.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /private/var/folders/xf/_tm0f94d66n8kr12tqwrylrr0000gn/T/cibw-run-g71pyn9q/cp312-macosx_arm64/build/venv/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /private/var/folders/xf/_tm0f94d66n8kr12tqwrylrr0000gn/T/cibw-run-g71pyn9q/cp312-macosx_arm64/build/venv/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      neoversen1 MAX_THREADS=64
    pc file directory: /private/var/folders/xf/_tm0f94d66n8kr12tqwrylrr0000gn/T/cirrus-ci-build/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /private/var/folders/xf/_tm0f94d66n8kr12tqwrylrr0000gn/T/cibw-run-g71pyn9q/cp312-macosx_arm64/build/venv/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /private/var/folders/xf/_tm0f94d66n8kr

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [9]:
a = np.random.random((2, 3, 5))



### 4. Print a.


In [12]:
print("a:\n", a)


a:
 [[[0.08164802 0.46630709 0.26623691 0.92706464 0.06838103]
  [0.09911737 0.5398828  0.44645752 0.12922415 0.3150913 ]
  [0.73632374 0.69218269 0.63323525 0.06995964 0.2944485 ]]

 [[0.52560743 0.05254197 0.39300609 0.3786208  0.64209947]
  [0.60394863 0.23296086 0.08844063 0.61422043 0.74664922]
  [0.64665106 0.70888501 0.94612734 0.53861131 0.41251659]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [13]:
b = np.ones((5, 2, 3))



### 6. Print b.


In [14]:
print("b:\n", b)


b:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [16]:
print("a.size:", a.size)
print("b.size:", b.size)
print("Same number of elements?", a.size == b.size)   # True, both have 30 elements


a.size: 30
b.size: 30
Same number of elements? True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
# 8. Are you able to add a and b? Why / why not?
# This will raise a ValueError because shapes are incompatible for broadcasting:
# a has shape (2, 3, 5) and b has shape (5, 2, 3).
# Uncomment to see the error:
# a + b




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
print("c.shape:", c.shape)


c.shape: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [21]:
# 10. Add a and c (now shapes match)
d = a + c                  # works because both are (2, 3, 5)
print("d.shape:", d.shape)

d.shape: (2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [22]:
print("a[0,0]:", a[0,0])
print("d[0,0]:", d[0,0])



a[0,0]: [0.08164802 0.46630709 0.26623691 0.92706464 0.06838103]
d[0,0]: [1.08164802 1.46630709 1.26623691 1.92706464 1.06838103]



### 12. Multiply a and c. Assign the result to e.


In [23]:
e = a * c                  # multiplying by ones
print("e equals a?", np.allclose(e, a))



e equals a? True




### 13. Does e equal to a? Why or why not?


In [24]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print("d_min:", d_min)
print("d_mean:", d_mean)
print("d_max:", d_max)



d_min: 1.0525419658038184
d_mean: 1.4432149165217796
d_max: 1.9461273445972656




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [26]:
f = np.empty_like(d)




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [27]:
# 16. Label values in f based on d
#  - > d_min and < d_mean  → 25
#  - > d_mean and < d_max  → 75
#  - == d_min              → 0
#  - == d_max              → 100
#  - == d_mean             → 50

f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_min] = 0
f[d == d_max] = 100
f[d == d_mean] = 50   # often there is no exact mean value for random floats




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [29]:
print("d:\n", d)
print("f (labels):\n", f)
print("Unique values in f:", np.unique(f))  # should be subset of {0,25,50,75,100}


d:
 [[[1.08164802 1.46630709 1.26623691 1.92706464 1.06838103]
  [1.09911737 1.5398828  1.44645752 1.12922415 1.3150913 ]
  [1.73632374 1.69218269 1.63323525 1.06995964 1.2944485 ]]

 [[1.52560743 1.05254197 1.39300609 1.3786208  1.64209947]
  [1.60394863 1.23296086 1.08844063 1.61422043 1.74664922]
  [1.64665106 1.70888501 1.94612734 1.53861131 1.41251659]]]
f (labels):
 [[[ 25.  75.  25.  75.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.   0.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  75. 100.  75.  25.]]]
Unique values in f: [  0.  25.  75. 100.]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
print("d:\n", d)
print("f (labels):\n", f)
print("Unique values in f:", np.unique(f))  # should be subset of {0,25,50,75,100}


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [30]:
# 18. Bonus: same labeling but with strings "A", "B", "C", "D", "E"
# A  → d_min
# B  → between d_min and d_mean
# C  → equal to d_mean
# D  → between d_mean and d_max
# E  → d_max

g = np.empty(d.shape, dtype="<U1")  # array of 1-char strings

g[(d > d_min) & (d < d_mean)] = "B"
g[(d > d_mean) & (d < d_max)] = "D"
g[d == d_min] = "A"
g[d == d_max] = "E"
g[d == d_mean] = "C"

print("g (string labels):\n", g)
print("Unique labels in g:", np.unique(g))

g (string labels):
 [[['B' 'D' 'B' 'D' 'B']
  ['B' 'D' 'D' 'B' 'B']
  ['D' 'D' 'D' 'B' 'B']]

 [['D' 'A' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'D']
  ['D' 'D' 'E' 'D' 'B']]]
Unique labels in g: ['A' 'B' 'D' 'E']
